// Generated by https://quicktype.io

export interface ProductoResponse {
    categoria:  string;
    desc1:      string;
    desc2:      string;
    producto:   string;
    resumen:    string;
    subtitulo1: string;
    subtitulo2: string;
}
// Generated by https://quicktype.io

export interface ProductoIDXResponse {
    categoria: string;
    cod:       string;
    titulo:    string;
    url:       string;
}
